services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dataset.sql:/docker-entrypoint-initdb.d/dataset.sql
    ports:
      - "5432:5432"

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/car_service
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
